### ISSUE TITLE
Please add Will and Drew as Translation Managers

### ISSUE THREAD

**Issue by anthonyfok** [OpenDRR/riskprofiler#102]
Hi @phil-evans,

Please ~~create a WordPress account for~~ add Will Chow (@wkhchow) and Drew Rotheram (@drotheram) as "Translation Managers" too.

Many thanks!

**Comment by anthonyfok** [comment]
I just realized I could see who the current translators are, and Will was already added! (Thanks!)

I was able to create an account for Drew also.  When you are free, could you please check if Drew is a "Translation Manager"?

Many thanks!

**Comment by phil-evans** [comment]
done!

**Comment by anthonyfok** [comment]
Awesome!  Thank you so much Phil!  Marking this issue as resolved!
