### ISSUE TITLE
Please provide WordPress database export (as of May 3 or 4, 2023)

### ISSUE THREAD

**Issue by anthonyfok** [OpenDRR/riskprofiler#103]
Hi @phil-evans,

Thank you for adding the new strings to the "rp" domain, which we've just finished translating into French, so I think we're ready for a release candidate (RC1) for deployment.

Could you please send a new WordPress database export for us to download?  On Slack over the #riskprofiler-wp channel would be ideal, as there may be encrypted passwords in the database export, so Slack seems a safer choice.  :-)

Many thanks!

**Comment by phil-evans** [comment]
sent in the #riskprofiler-wp channel on slack

**Comment by anthonyfok** [comment]
Super!  Received!  Thanks so much!  Closing this one as completed also. 

I'll send another request for DB export tomorrow after I get the various issues fixed on my end.  Many thanks!
