### ISSUE TITLE
Some untranslatable strings in charts?

### ISSUE THREAD

**Issue by anthonyfok** [OpenDRR/riskprofiler#104]
Hi @phil-evans,

Sorry for bothering you with these minute details, but I noticed that some strings are still in English despite all current strings in the `rp` domain has been translated, e.g.:

> ![image](https://user-images.githubusercontent.com/1274764/236040931-891d55b6-9f03-48e9-9541-c5c5dd87c32b.png)

but when the mouse hovers over a bar, it shows "people" and "buildings" in English, for example:

> ![image](https://user-images.githubusercontent.com/1274764/236039715-9fb3c683-9a55-4841-a579-4b9004fc8914.png)
> ![image](https://user-images.githubusercontent.com/1274764/236040004-ebe96f45-690a-4df5-b81d-d4ccc8854a8f.png)

And, if it is not too much trouble, it would be great if the pop-up menu for downloading the data as CSV/PDF could be translated too:

> ![image](https://user-images.githubusercontent.com/1274764/236040665-24c9a13e-73de-4ddb-bd67-d549b27b498c.png)

Many thanks!

**Comment by phil-evans** [comment]
same issue here as #105 - the label values need to be translated in each indicator post:

![Screen Shot 2023-05-04 at 9 18 35 AM](https://user-images.githubusercontent.com/18401550/236203115-a46a889d-8beb-4394-91d2-77534ab57fb4.png)

**Comment by anthonyfok** [comment]
Oops, my oversight indeed!  Thanks @phil-evans for showing me how to get these translated!
Closing this issue (while opening a new one for the chart download menu in #108)
