### ISSUE TITLE
Mouse-over on map for Probabilistic Risks shows "buildings" instead of "bâtiments" for French page

### ISSUE THREAD

**Issue by anthonyfok** [OpenDRR/riskprofiler#105]
Hi @phil-evans,

On the map for Probabilistic Risks, mouse-over an area shows "_x_ buildings" instead of "_x_ bâtiment(s)":

![image](https://user-images.githubusercontent.com/1274764/236044506-d677a4ad-bf3c-4c32-8aec-dcc5e82274a9.png)

The French translations for "people" and for dollar amount seem OK though.

Many thanks!

**Comment by phil-evans** [comment]
each indicator post has a set of label fields that needs to be translated:

![Screen Shot 2023-05-04 at 9 18 35 AM](https://user-images.githubusercontent.com/18401550/236202723-4e3392d7-1061-47c2-a9d8-22ffc5d2631a.png)

**Comment by anthonyfok** [comment]
Thank you so much for showing me how to reach those translations!  Very helpful!
I have decided to change both the English and French to e.g. "building(s)" and « bâtiment(s) » (parenthetical plurals) and will see if the team likes it or not, haha!  Closing this issue.
