### ISSUE TITLE
Hover over and expand Building Description and Design level

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/riskprofiler#27]
Detailed Description on hover

Expand URMasonry RMasonry to Unreinforced/Reinforced

<img width="1385" alt="Screen Shot 2022-05-13 at 10 35 24 AM" src="https://user-images.githubusercontent.com/7228960/168337739-e0c1be8d-05a0-4e20-8707-2aff1cf19f81.png">

expand PC MC LC HC to full text pre-code, mid-code low-code, high code

**Comment by phil-evans** [comment]
done

![Screen Shot 2022-05-24 at 9 55 37 AM](https://user-images.githubusercontent.com/18401550/170039856-cf9fec6c-d31f-4b7d-bb35-a414195efcdb.png)
![Screen Shot 2022-05-24 at 9 55 18 AM](https://user-images.githubusercontent.com/18401550/170039859-5d7c531c-12d4-474f-960d-4ee4d4731776.png)
