### ISSUE TITLE
DSRA scenario footprints

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/riskprofiler#28]
DSRA Scenarios should show the footprint of the shakemap rather than the bounding box. Scenario extents are available if needed
<img width="1362" alt="Screen Shot 2022-05-13 at 11 22 53 AM" src="https://user-images.githubusercontent.com/7228960/168344339-15036548-595f-49a5-9c26-663fe19c24c0.png">

**Comment by jvanulde** [comment]
Duplicates #37 which is closed.
