### ISSUE TITLE
Round off Dollar value for loss values

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/riskprofiler#29]
Significant digits does not represent model uncertainty. Tiegan, can you advise on appropriate rounding for display?

<img width="892" alt="Screen Shot 2022-05-13 at 11 24 22 AM" src="https://user-images.githubusercontent.com/7228960/168344526-1f3eba5e-97a8-4aa3-b182-bd620d2d4ef2.png">

**Comment by drotheram** [comment]
@tieganh says to round to 3 significant digits. i.e. $13.5 B

**Comment by phil-evans** [comment]
done

![Screen Shot 2022-05-26 at 3 21 47 PM](https://user-images.githubusercontent.com/18401550/170551951-92a1b0c5-0a11-4133-84e7-c5f353e9de2b.png)

**Comment by jvanulde** [comment]
@drotheram shouldn't we do this in the list view as well?

**Comment by drotheram** [comment]
Yes, this should essentially be implemented site wide

**Comment by plesueur** [comment]
Hey folks, here is a rounding scheme to implement for this issue (both scenarios and probabilistic data):

if x = 0, display '0'
if x < 1000, display 'less than 1000'
if x >= 1000 display two significant figures (e.g. 23,456 becomes 23 thousand; 234,567 becomes 230 thousand; 2,345,678 becomes 2.3 million)

When this is complete, I think one of the science team should have a look to confirm it makes sense (there may be weird cases that show up). @phil-evans, if you notice anything that doesn't make sense let us know.

**Comment by anthonyfok** [comment]
Superseded by #64
