### ISSUE TITLE
Colour DSRA epicentres on breakout

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/riskprofiler#30]
Faint grey dots hard to see. Can we colour these large and red similar to how they appear before breakout:
<img width="1205" alt="Screen Shot 2022-05-13 at 11 26 44 AM" src="https://user-images.githubusercontent.com/7228960/168344926-e6230f8d-9ed2-4d76-ad51-747a52e11dac.png">
<img width="1195" alt="Screen Shot 2022-05-13 at 11 27 39 AM" src="https://user-images.githubusercontent.com/7228960/168344978-56c14bd3-76fb-48e3-b5d9-1ae0b48cc55b.png">

**Comment by phil-evans** [comment]
made the markers dark red by default, and added the pulsing icon to the scenario on the initial selection instead of on the detail view:

![Screen Shot 2022-05-20 at 9 41 47 AM](https://user-images.githubusercontent.com/18401550/169530295-3c4d10f2-d0dc-4b37-8e9d-d06887c936f7.png)

**Comment by jvanulde** [comment]
Complete.
