### ISSUE TITLE
Rename "Fatalities" Tab title to Injuries

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/riskprofiler#32]
Rename on-click polygon to "people"
<img width="856" alt="Screen Shot 2022-05-18 at 9 18 00 PM" src="https://user-images.githubusercontent.com/7228960/169203323-7f703545-57d6-4e50-ae05-1383334d5055.png">

**Comment by phil-evans** [comment]
done
![Screen Shot 2022-05-19 at 3 35 19 PM](https://user-images.githubusercontent.com/18401550/169375147-5c48a132-fff9-4476-ae82-ab9f49a10c2f.png)

**Comment by jvanulde** [comment]
Confirmed as complete.
