### ISSUE TITLE
Ensure fractions of buildings and people are cast to integers

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/riskprofiler#33]
<img width="1250" alt="Screen Shot 2022-05-18 at 9 21 48 PM" src="https://user-images.githubusercontent.com/7228960/169203701-9daaef38-e1c4-4af5-89c3-4dc1c65f28c0.png">

**Comment by phil-evans** [comment]
this can be done using the aggregation settings for each indicator post in wordpress - i've updated the building/people related ones to show 0 decimal places:
![Screen Shot 2022-05-19 at 3 16 33 PM](https://user-images.githubusercontent.com/18401550/169372120-020fa11b-f82a-44da-91b5-93951f3e5ff8.png)

**Comment by drotheram** [comment]
Excellent! We can close this issue on a merge of those changes then
