### ISSUE TITLE
Change Colouring of Design Level to reflect relative risk

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/riskprofiler#34]
Precode - black
Low code - red
Mid Code - orangey-yellow
High Code - Green
<img width="632" alt="Screen Shot 2022-05-18 at 9 26 48 PM" src="https://user-images.githubusercontent.com/7228960/169204922-cfd9bcf0-4973-4f05-89cc-5c37dd1bb6e7.png">

**Comment by phil-evans** [comment]
done
![Screen Shot 2022-05-19 at 3 25 32 PM](https://user-images.githubusercontent.com/18401550/169373379-739aa7ed-c79b-43b2-811b-c12ee510c0b0.png)
