### ISSUE TITLE
Scenario extents representation

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/riskprofiler#37]
I understood that we would display the scenario extents as the boundary of the scenario and not a bounding box. @tieganh can you confirm if this is still the preferred approach?

The scenario extents are available in the API at: https://geo-api.riskprofiler.ca/collections/opendrr_shakemap_scenario_extents_v1.4.0/items?lang=en_US

**Comment by phil-evans** [comment]
thanks for providing those extents @jvanulde - i've added them now, looks great:

![Screen Shot 2022-05-30 at 10 03 58 AM](https://user-images.githubusercontent.com/18401550/170998307-a37da003-81f8-43b1-ae81-bf4b0774066f.png)
![Screen Shot 2022-05-30 at 10 04 05 AM](https://user-images.githubusercontent.com/18401550/170998311-3becbc9b-38f4-475a-b1e2-38da0f2320aa.png)

**Comment by jvanulde** [comment]
Thanks @phil-evans!
