### ISSUE TITLE
Downloads Pages for scenarios - reorder

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/riskprofiler#39]
The order should go based on polygon size:

Aggregated Buildings

Settlement Area

Census Subdivision

<img width="1215" alt="Screen Shot 2022-06-02 at 3 10 25 PM" src="https://user-images.githubusercontent.com/7228960/171746754-c89dcc9f-927c-4a43-983f-5d86b7c4d5cb.png">

**Comment by phil-evans** [comment]
done

**Comment by jvanulde** [comment]
Complete.
