### ISSUE TITLE
Downloads link for Val Des Bois is broken

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/riskprofiler#40]
<img width="1208" alt="Screen Shot 2022-06-02 at 3 16 08 PM" src="https://user-images.githubusercontent.com/7228960/171747509-c10d39ae-4755-4ff5-b10b-a52339e0e22a.png">
Case sensitive, points to:

https://github.com/OpenDRR/earthquake-scenarios/blob/master/FINISHED/SCM7p5_valdesbois.md

should point to:

https://github.com/OpenDRR/earthquake-scenarios/blob/master/FINISHED/SCM7p5_ValDesBois.md

**Comment by phil-evans** [comment]
this is fixed

**Comment by jvanulde** [comment]
Complete.
