### ISSUE TITLE
PSRA indicator list

### ISSUE THREAD

**Issue by phil-evans** [OpenDRR/riskprofiler#42]
hoping to get this list vetted with any additions/subtractions/re-ordering that's required for the 'probabilistic risks' overlay menu:

- Average annual fatalities
- Average annual fatality rate
- Average Building Asset Loss Ratio
- Average Capital Asset Loss (Building + Contents) Ratio
- Building Asset Loss
- Buildings with Complete Damage
- Buildings with Extensive Damage
- Buildings with Moderate Damage
- Buildings with Slight Damage
- Capital Asset Loss (Building + Contents)
- Collapsed Buildings
- Loss to Building Contents
- Loss to Nonstructural Building Components
- Loss to Structural Building Components
- Probability of Building Collapse
- Probability of Complete Damage
- Probability of Extensive Damage
- Probability of Moderate Damage
- Probability of Slight Damage

![Screen Shot 2022-06-13 at 10 30 10 AM](https://user-images.githubusercontent.com/18401550/173365265-304f2c4e-edb1-4e69-bd96-904bad7f576f.png)

**Comment by tieganh** [comment]
Hey @phil-evans - thanks for asking. Note that @plesueur and I have been finalizing the names for these, so I've assigned him so he can give the updates. Here's the order I would put them in, and the ones I would omit for simplicity. We can always add back in later after engagement if people want to know those things. @JulieVdV any thoughts?

- Average annual fatalities
- Average annual fatality rate
- Capital Asset Loss (Building + Contents)
- Average Capital Asset Loss (Building + Contents) Ratio
- Buildings with Slight Damage
- Probability of Slight Damage
- Buildings with Moderate Damage
- Probability of Moderate Damage
- Buildings with Extensive Damage
- Probability of Extensive Damage
- Buildings with Complete Damage
- Probability of Complete Damage
- Collapsed Buildings
- Probability of Building Collapse
- ~~Loss to Building Contents~~
- ~~Loss to Nonstructural Building Components~~
- ~~Loss to Structural Building Components~~
- ~~Building Asset Loss~~
- ~~Average Building Asset Loss Ratio~~
