### ISSUE TITLE
Round the dollar value for asset loss on scenarios?

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/riskprofiler#43]
Currently we are showing a value down to the cent. @tieganh does it make more sense to round it to the nearest million?

<img width="1331" alt="Screen Shot 2022-06-23 at 8 43 05 PM" src="https://user-images.githubusercontent.com/2255248/175457885-571103a9-2a2a-4160-94c0-17b3ed24a3cf.png">

**Comment by phil-evans** [comment]
for this one i wrote a function that will round the output based on the number - i thought this made the most sense for usability/readability (a number like $42,307 would show as $0.0 billion). it's hardcoded to format this way for the indicators under the 'dollars' category, but we could have it be set by indicator in WP (i.e. if we wanted to do the same for the tonnes value mentioned in #46)

![1](https://user-images.githubusercontent.com/18401550/177770793-df2e783d-c16d-4370-a294-f5a36a472180.png)
![2](https://user-images.githubusercontent.com/18401550/177770802-8f0a2535-d40c-425a-a130-205ccd07d963.png)
![3](https://user-images.githubusercontent.com/18401550/177770803-22015cac-8395-4771-876b-4992042d235b.png)
![4](https://user-images.githubusercontent.com/18401550/177770809-698e1329-031e-4e4f-8b00-e7ab38315105.png)

**Comment by anthonyfok** [comment]
Superseded by #64
