### ISSUE TITLE
Round tonnes value?

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/riskprofiler#46]
Perhaps we should round to millions of tonnes as per the legend? @drotheram, @tieganh what do you think?

<img width="1732" alt="Screen Shot 2022-06-24 at 11 34 28 AM" src="https://user-images.githubusercontent.com/2255248/175644833-348a9db7-f35d-4ca7-9fec-6b701a8fbeb2.png">

**Comment by phil-evans** [comment]
i think this makes sense but maybe just for values over a certain threshold - otherwise a lot of the pale yellow areas would show the value as 0.0 million tonnes..

**Comment by anthonyfok** [comment]
Superseded by #64
