### ISSUE TITLE
Multiple scenario extents shown on map

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/riskprofiler#49]
To replicate:

1. load a scenario extent by clicking on the left menu 
2. click on a scenario point in the map for an alternate scenario
3. select another scenario in the left menu
4. two scenario extents will be shown in the map (see attached screenshot)

<img width="1377" alt="Screen Shot 2022-06-29 at 8 35 47 AM" src="https://user-images.githubusercontent.com/2255248/176477625-e9cd5e6b-2152-4884-8b7f-98c2775e9111.png">

**Comment by phil-evans** [comment]
fixed in next commit
