### ISSUE TITLE
 Assess options for static site generators

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/riskprofiler#5]
Requirements:

- Latest build to be deployed on GitHub pages in the riskprofiler repository
- Stable development build to be deployed in S3 in our development AWS environment
- Release build to be deployed in S3 in our production environment
- Must be compatible with [wet-boew](https://github.com/wet-boew)
- work with continuous integration platform on AWS
- pull in code from other repositories (i.e. info-viz)
- support ReactJS

Options include:

- Hugo which supported on AWS
- Jekyll for which a version of wet-boew exists

Demonstrate most suitable option(s)

**Comment by FaisalNkutu** [comment]
1. Clone info-viz repo and launched it with sample data
2. Installed Jerkyll and Hugo
3. Started working with them and comparing them

**Comment by jvanulde** [comment]
Demonstrated. Closing issue.
