### ISSUE TITLE
Orphan 'get started' tab on home page

### ISSUE THREAD

**Issue by jvandevalk** [OpenDRR/riskprofiler#54]
There's a 'get started' tab on the home page that doesn't go anywhere. Is it easy to add several other tabs there? If so, I can suggest some tabs to add beside it, otherwise, I think we should remove it as there's no logical place to send that particular tab.

**Comment by phil-evans** [comment]
fixed

**Comment by anthonyfok** [comment]
Fixed by @phil-evans in commit OpenDRR/h7-riskprofiler@e16ef8a823c185df5af0f21357c203443df263b2
