### ISSUE TITLE
Colour of heading when selected

### ISSUE THREAD

**Issue by jvandevalk** [OpenDRR/riskprofiler#59]
When you select Earthquake Scenarios and are on that page, the Earthquake Scenarios header has a white background and is clearly selected. When you select Probabilistic Risks, it does not get a white background to show it's selected - Earthquake Scenarios stays white and it is counter-intuative that you are on the probabilistic risks page. See screenshots below. Note, the difference is if you go from mainpage -> scenarios -> probabilistic (first image), or mainpage -> probabilistic (second image). 

![image](https://user-images.githubusercontent.com/103536301/186005484-1e9333cb-abd9-4038-acf2-f85c2d907763.png)
![image](https://user-images.githubusercontent.com/103536301/186005544-8ccffb35-06ee-493d-9a17-29218356d68d.png)

**Comment by phil-evans** [comment]
done

**Comment by anthonyfok** [comment]
Fixed by @phil-evans in commit OpenDRR/h7-riskprofiler@33fb9fa367810b73b9bd90ed188a1b283af40b9e
