### ISSUE TITLE
RiskProfiler website still using default WordPress favicon

### ISSUE THREAD

**Issue by anthonyfok** [OpenDRR/riskprofiler#61]
The RiskProfiler website in beta is still using the default WordPress favicon (website icon), i.e. the _W_ logo in white with blue background:

![w-logo-blue-white-bg.png](https://beta.riskprofiler.ca/site/wp-includes/images/w-logo-blue-white-bg.png)

This needs to be replaced with our own logo/favicon, preferably before launch.

**Comment by phil-evans** [comment]
done

**Comment by anthonyfok** [comment]
Fixed by @phil-evans in commit OpenDRR/h7-riskprofiler@386189db9acdae599e75c24a7ee8bf87c10469e9
