### ISSUE TITLE
Change colors on the 'By Design Level' chart 

### ISSUE THREAD

**Issue by tieganh** [OpenDRR/riskprofiler#63]
Pre-code should be black, low-code should be red, moderate-code should be yellow, and high-code should be green.

**Comment by phil-evans** [comment]
fixed - we had it the colours set this way before but the order of the columns got switched around in my script at some point. you should see this now:

![Screen Shot 2022-09-09 at 9 46 00 AM](https://user-images.githubusercontent.com/18401550/189353566-19e0be59-54e2-45b7-8dd2-4f5ec1c7c616.png)
