### ISSUE TITLE
Change names/descriptions for probabilistic list in RP

### ISSUE THREAD

**Issue by tieganh** [OpenDRR/riskprofiler#65]
Since we won't have hover-overs, we need to provide some additional information on our probabilistic indicators/variables on the probabilistic landing page. Attached is an image showing how we want the changes to appear. We'd like to go with Option 2. I'm also attaching an updated list of the names and descriptions. 

[probabilistic_landing_page_v2.xlsx](https://github.com/OpenDRR/riskprofiler/files/9552542/probabilistic_landing_page_v2.xlsx)
![Screen Shot 2022-09-06 at 1 28 42 PM](https://user-images.githubusercontent.com/59665171/189781051-02c74edc-51b3-454f-962b-44d54eff3e3a.png)

**Comment by phil-evans** [comment]
done - templates updated with next commit and description text will be included in the next database export

![Screen Shot 2022-09-13 at 9 06 20 AM](https://user-images.githubusercontent.com/18401550/189896967-6e9a74cf-451d-4cc9-946c-01c5089ca079.png)

**Comment by jvandevalk** [comment]
@tieganh This is ready to close - I think you have to close as you opened?
