### ISSUE TITLE
DSRA 'Explore Scenario' functionality broken

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/riskprofiler#66]
Functionality broken on most recent beta.riskprofiler.ca deployment
Works on H7 work site
<img width="1160" alt="Screen Shot 2022-09-12 at 5 54 43 PM" src="https://user-images.githubusercontent.com/7228960/189784054-13f4d7c7-1fed-419b-9903-81e423d0a470.png">

**Comment by phil-evans** [comment]
the error is that the 'page tour' JS is missing - it's a WP plugin that was included in a recent commit, but we'll need a fresh export of the database that has the plugin activated. i'll send a new SQL dump to you this morning @anthonyfok

**Comment by tieganh** [comment]
This seems like it is working now. Closing.
