### ISSUE TITLE
mismatch for probabilistic risk - seismic risk index - absolute risk score / normalized risk score

### ISSUE THREAD

**Issue by wkhchow** [OpenDRR/riskprofiler#69]
Comparing risk profiler website and my postgis db (v1.4.3), the risk index scores do not match v1.4.3 version. Newest version has revised formula and score adjusted from 0 - 100.

![image](https://user-images.githubusercontent.com/59062243/190510924-4717c22b-4575-4375-8478-91de178d7d0e.png)

![image](https://user-images.githubusercontent.com/59062243/190511336-38e6fa23-22bf-4c5d-a690-f14447b01f10.png)

**Comment by anthonyfok** [comment]
## Progress Log

### Thu 2022-09-15:

* @wkhchow shared his findings of risk score mismatch during RiskProfiler weekly meeting H7
* @phil-evans confirmed that "those risk scores are indeed pulling from the selected feature properties in the vector tile".
* @wkhchow filed this GitHub issue
* @DamonU2 sent a Google Drive link to the two tile sets that he was able to complete previously to @anthonyfok to get the ball rolling:
  * psra_canada_expected_loss_500yr.zip (2022-07-20, 1.3 GiB, SHA256: 37325bf1172cc36479f524c3433fc9cf9dcfd7306fb0f6b538e805a9383729fc)
  * psra_indicators_csd.zip (2022-08-04, 2.67 GiB, SHA256: 440517aaaf1ae4474dba2b34a558d7ed4b6fce92d8d91ea4a6ed9588057c8d16)
* @wkhchow got GeoServer installed and running on his Windows EC2 instance on AWS

### Fri 2022-09-16:

* @DamonU2 figured out how to run GeoServer natively on Windows, without Docker, thus the vector tiles are written directly to NTFS which is unencumbered by things like Linux ext4 inode limit
* @DamonU2 met with @wkhchow (online video call) and walked through the procedure on [installing the Vector Tiles Extension](https://docs.geoserver.org/stable/en/user/extensions/vectortiles/install.html) and configuring GeoServer for OpenDRR PSRA vector tile generation.
* @wkhchow started generating psra_indicators_s vector tiles on his Windows EC2 instance and let it ran over the weekend.

### Tue 2022-09-20:

* @wkhchow reported success and provided a OneDrive link to psra_indicators_s vector tiles:
  * psra_indicators_s/EPSG_4326.7z (1.08 GiB, SHA256: 954c68d38e72adb955d48b8ae04daa673b9d1fd4ba7dd8c94f1d3fac9158616d)
  * psra_indicators_s/EPSG_900913.7z (987 MiB, SHA256: c21dd31ba4fe50c87cf39c1c58fb02eca0ed005d65c6aeff2e4bfc816b5f2cca)

### Thu 2022-09-22:

* @anthonyfok [removed empty *.pbf files and recompressed them as .tar.xz](https://github.com/OpenDRR/opendrr/wiki/Vector-Tiles-with-GeoServer-Notes#compressingarchiving-the-vector-tiles-for-distribution) (on SSD for speed, on btrfs filesystem to avoid ext4 inode limit) and sent the files via Backblaze B2 links to @arashmalekz:
  * psra_canada_expected_loss_500yr.tar.xz (82MiB, SHA256: 4fb0e1838ffce1eec8de8eafec8f6467de3d6f0ade647d716d8c499a4ed0f71f)
  * psra_indicators_csd.tar.xz (118 MiB, SHA256: 1c10531b4ba94a6d372043cca81fbbf2d004740732f228ee6c0a08cf940041cb)
  * psra_indicators_s.tar.xz (2.0 GiB, SHA256: c7ca22eed41be316e42b2f41d92df09a35f23d5fc64748addcfd0e3f43becc24)
* @arashmalekz began uploading to AWS S3

**Comment by anthonyfok** [comment]
### Mon 2022-09-26

* @arashmalekz reported the new vector tile caches files have been uploaded.

### Tue 2022-09-27

* @wkhchow checked the PSRA tiles on H7 work site and our beta site and confirmed that the correct normalized risk scores  are now displayed.

---

@wkhchow @drotheram I'll let you close this issue when ready.  :-)

**Comment by wkhchow** [comment]
Spot checked a few random areas and checked with above screenshot area on h7 work / beta site. Looks like this issue is now fixed.

![image](https://user-images.githubusercontent.com/59062243/192594610-05aa006c-b84c-404b-94ef-a05c91980498.png)
