### ISSUE TITLE
Changes to page names and adding sub-pages

### ISSUE THREAD

**Issue by jvandevalk** [OpenDRR/riskprofiler#71]
1. Change main buttons / tabs to the following to use active language:

    - [x] Explore Earthquake Scenarios
    - [x] Consider Probabilistic Earthquake Risk
    - [x] Learn More (replace About)
    - [x] Download Data
    - [x] Contact Us
    - [x] *Delete* Training

2. Other changes:

    - [x] Remove space in "Risk Profiler" wherever applicable (three instances in bottom header, also main logo on top left)
    - [x] Remove 'daytime' from list of injury severity in Earthquake Scenario menu

3. Additional pages for the 'Learn More' (formerly About) tab

    - [x] General Information
    - [x] Uncertainties and Intended Use
    - [x] Earthquake Scenario Information
    - [x] Probabilistic Earthquake Risk
    - [x] Training Materials
    - [x] Frequently Asked Questions
    - [x] Glossary
    - [x] Additional Documentation
    - [x] Taking Action
    - [x] Review the Disclaimer

Also, is there an easy way to edit the wordpress with additional, minor items?

**Comment by phil-evans** [comment]
hi @jvandevalk, if you take a look at the 'pages' section at http://riskprofiler.habitatseven.work/site/wp-admin/ you'll see the sub-pages under the 'learn more' section ready for updating with content:

![Screen Shot 2022-10-07 at 12 36 54 PM](https://user-images.githubusercontent.com/18401550/194593054-246d6ff9-4b72-4b2d-921c-c7386af99f6c.png)

i created a simple template for these pages with the sub-nav on the right side to reflect the example you showed on our call yesterday - if you edit any of these pages you'll find the text block where the text can be added:

![Screen Shot 2022-10-07 at 12 39 45 PM](https://user-images.githubusercontent.com/18401550/194593565-8134557c-94e7-4031-b627-fe363505f1a8.png)

feel free to poke around in the WP admin and let me know if you have any questions/issues.

**Comment by jvandevalk** [comment]
Thanks Phil - it looks great! I've started adding content to a few pages, and had success changing the text on the probabilistic landing page - this is working well. 

- [ ] I updated the contact us page and put in the email we want people to use. Is it easy to make this a web form (type name, sender email and message in boxes) rather than list the email text?

**Comment by phil-evans** [comment]
hey @jvandevalk - unfortunately we won't be able to implement a contact form at this stage as the production version will be totally static and not able to run any server-side scripts that are required for processing a form.

**Comment by jvandevalk** [comment]
Understandable! Thank you for hiding the email.
