### ISSUE TITLE
Probabilistic Risk Data Labels

### ISSUE THREAD

**Issue by jvandevalk** [OpenDRR/riskprofiler#72]
Can we put the data label (in this case 'probability of slight damage) in the pop-up box that appears over the map. See screenshot below.

![image](https://user-images.githubusercontent.com/103536301/194136916-2e2505f2-2a9e-4724-acee-94798a8ecf41.png)

**Comment by phil-evans** [comment]
done

**Comment by phil-evans** [comment]
just realized this hadn't been updated online - should look like this now:

![Screen Shot 2022-10-12 at 3 15 14 PM](https://user-images.githubusercontent.com/18401550/195417994-5c03b08b-8544-4642-8499-44306703c412.png)
![Screen Shot 2022-10-12 at 3 15 08 PM](https://user-images.githubusercontent.com/18401550/195418000-3a19e997-3d79-434b-b276-36ea2e3416b0.png)
