### ISSUE TITLE
Other website text changes

### ISSUE THREAD

**Issue by jvandevalk** [OpenDRR/riskprofiler#73]
Can we add the GEM logo to the bottom of the main pages? Let me know who can tackle this and I will send them the high resolution logo. 

Can we remove 'daytime' from all the injuries parameters listed in the scenario section?

**Comment by jvandevalk** [comment]
Can we change 'financial loss to assets' to 'economic loss to building contents' in the scenarios section? and 
'Financial loss to buildings' to 'Economic loss to buildings', also in the scenarios section?

**Comment by phil-evans** [comment]
2nd and 3rd requests are done:

![Screen Shot 2022-10-06 at 2 39 55 PM](https://user-images.githubusercontent.com/18401550/194381930-98818c7d-4bce-4a32-913c-edfafac5b665.png)
![Screen Shot 2022-10-06 at 2 38 02 PM](https://user-images.githubusercontent.com/18401550/194381933-acf569d6-16c1-45b9-8238-85af885e1a0e.png)

if you could post the GEM logo here @jvandevalk then i'll add it

**Comment by jvandevalk** [comment]
Fantastic! The logo is below: 
![GEM-LOGO-Red-RGB-300DPI](https://user-images.githubusercontent.com/103536301/194382275-b6bd613b-ba09-44de-8361-f2355252c076.png)

**Comment by jvandevalk** [comment]
- [x] Hello, another request - can you help me with the formatting of the 'table' in the glossary page? I've put a table into the text content and the formatting appears to be working, but I can't make the table boundaries show up so it looks fairly jumbled. I've managed to add a border around the whole table, but not internal borders yet.

**Comment by jvandevalk** [comment]
Two landing page changes I wasn't able to make: 
- [x] add 'Tools to help Canadians build resiliency to seismic risk through planning and emergency management.' as a byline somewhere near the 'Earthquake risk information for disaster risk reduction in Canada' if possible. 
- [x] For the 'Learn More' carousel on the bottom of the main page, the boxes should say and direct to the following: 
Understand the project - Read about this project and appropriate use of RiskProfiler information. (http://riskprofiler.habitatseven.work/learn-more/)
Explore training materials - Use resources designed to help you understand and navigate RiskProfiler. (http://riskprofiler.habitatseven.work/learn-more/training-materials/)
Read Frequently Asked Questions - Understand the data through ‘FAQs’ (http://riskprofiler.habitatseven.work/learn-more/frequently-asked-questions/)
See glossary - find clarification on all acronyms and terms used throughout RiskProfiler (http://riskprofiler.habitatseven.work/learn-more/glossary/)
Additional documentation - Looking for technical documentation of the data and modelling? Download all published documents here. (http://riskprofiler.habitatseven.work/learn-more/additional-documentation/)
Take action - Explore these resources to learn about how to to take risk reduction action in your community (http://riskprofiler.habitatseven.work/learn-more/taking-action/)
Contact Us - Get connected to additional resources and ask questions to the team.   (http://riskprofiler.habitatseven.work/contact/)

**Comment by jvandevalk** [comment]
- [x] Can the order of the 'Learn More' and 'Download Data' buttons be reversed? 

![image](https://user-images.githubusercontent.com/103536301/195176064-0b01f2d6-4a16-4cd3-9e2b-c94ecc53ab0a.png)

**Comment by phil-evans** [comment]
i believe this one's ready to close @jvandevalk
