### ISSUE TITLE
Ratio = eCr_Fatality? Missing Data in Probabilistic Average Annual Fatalities Ratio

### ISSUE THREAD

**Issue by jvandevalk** [OpenDRR/riskprofiler#74]
As shown in screenshot below, the data appears to be missing from the Average Annual Fatalities Ratio in some cases, and is replaced with eCr_Fatality

![image](https://user-images.githubusercontent.com/103536301/194137631-205f9c3e-951c-4faa-82bc-9d76e759fb32.png)

**Comment by phil-evans** [comment]
fixed - there was a bug in handling 0 values. also updated the number formatting method for the other figures in that table:

<img width="529" alt="Screen Shot 2022-10-06 at 10 01 47 AM" src="https://user-images.githubusercontent.com/18401550/194319616-b0b5d458-690c-4d0c-ad38-328eb3938b44.png">

**Comment by drotheram** [comment]
Can we close this issue?
