### ISSUE TITLE
Add 5 new DSRA scenarios

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/riskprofiler#76]
ES enpoints, geopackages and vector tiles ready for the following 5 new scenarios:

dsra_acm4p9_capilano5
dsra_acm5p3_duncan
dsra_acm7p4_burwashlanding
dsra_scm5p0_montreal
dsra_scm5p5_ottawa

**Comment by phil-evans** [comment]
@drotheram is there somewhere i can grab the meta data for each of these scenarios? i.e. description, magnitude, epicentre? i don't see them in geo-api.riskprofiler.ca

**Comment by drotheram** [comment]
Updated pygeoapi configuration is in progress. Do these markdowns have enough info?


https://github.com/OpenDRR/DSRA-processing/blob/six-new-scenarios-sep-2022/FINISHED/ACM4p9_Capilano5.md
https://github.com/OpenDRR/DSRA-processing/blob/six-new-scenarios-sep-2022/FINISHED/ACM5p3_Duncan.md
https://github.com/OpenDRR/DSRA-processing/blob/six-new-scenarios-sep-2022/FINISHED/ACM7p4_BurwashLanding.md
https://github.com/OpenDRR/DSRA-processing/blob/six-new-scenarios-sep-2022/FINISHED/SCM5p0_Montreal.md
https://github.com/OpenDRR/DSRA-processing/blob/six-new-scenarios-sep-2022/FINISHED/SCM5p5_Ottawa.md

**Comment by phil-evans** [comment]
thanks @drotheram, these have what i needed - the scenarios are in WP now, just waiting for the shakemaps on the frontend

**Comment by drotheram** [comment]
Please do not include the Duncan event for now. There appears to be an issue with it

**Comment by phil-evans** [comment]
the 4 scenarios are up and running now

**Comment by anthonyfok** [comment]
Thank you Phil!

This issue was fixed back in October 2022.  There have been renames to 3 of the 4 scenarios, but such subsequent work are being tracked in other issues such as

- OpenDRR/earthquake-scenarios#74

Closing this issue now.
