### ISSUE TITLE
Adjust max colour stretch values in PSRA maps

### ISSUE THREAD

**Issue by drotheram** [OpenDRR/riskprofiler#79]
Some PSRA maps look like a 'sea of cream colour' it appears the max value of the colour stretch is too  

<img width="1252" alt="Screen Shot 2022-10-14 at 9 47 41 AM" src="https://user-images.githubusercontent.com/7228960/195899749-43070254-44b1-4536-af62-befa1fe35b69.png">

Here are appropriate global max values for 
*CSD level
Average Annual Fatalities baseline = 0.902588
Average Annual Fatalities retrofit = 0.378745
Annual Probability of Fatality baseline = 0.000007
Annual Probability of Fatality retrofit = 0.000005
Annual Building and Contents Economic Loss baseline = 72955761.703502
Annual Building and Contents Economic Loss retrofit = 52512144.431167
Annual Building and Contents Economic Loss Ratio baseline = 0.001840
Annual Building and Contents Economic Loss Ratio retrofit = 0.001449
Buildings with Slight Damage over 50 years baseline = 10158.395161
Buildings with Slight Damage over 50 years retrofit = 9462.957636
Probability of Buildings with Slight Damage over 50 years baseline = 0.656037
Probability of Buildings with Slight Damage over 50 years retrofit = 0.510192
Buildings with Moderate Damage over 50 years baseline = 1283.647850
Buildings with Moderate Damage over 50 years retrofit = 1081.433265
Probability of Buildings with Moderate Damage over 50 years baseline = 0.151228
Probability of Buildings with Moderate Damage over 50 years retrofit = 0.094374
Buildings with Extensive Damage over 50 years baseline = 438.398155
Buildings with Extensive Damage over 50 years retrofit = 343.500585
Probability of Buildings with Extensive Damage over 50 years baseline = 0.070198
Probability of Buildings with Extensive Damage over 50 years retrofit = 0.040815
Buildings with Complete Damage over 50 years baseline = 806.128925
Buildings with Complete Damage over 50 years retrofit = 386.938465
Probability of Buildings with Complete Damage over 50 years baseline = 0.136453
Probability of Buildings with Complete Damage over 50 years retrofit = 0.073975
Collapsed Buildings over 50 years baseline = 60.637667
Collapsed Buildings over 50 years retrofit = 29.549729
Probability of Collapsed Buildings over 50 years baseline = 0.011617
Probability of Collapsed Buildings over 50 years retrofit = 0.005918
*SAUID level
Average Annual Fatalities baseline = 0.027641
Average Annual Fatalities retrofit = 0.007526
Annual Probability of Fatality baseline = 0.00299
Annual Probability of Fatality retrofit = 0.000008
Annual Building and Contents Economic Loss baseline = 1655867.52502
Annual Building and Contents Economic Loss retrofit = 1434621.120156
Annual Building and Contents Economic Loss Ratio baseline = 0.004127
Annual Building and Contents Economic Loss Ratio retrofit = 0.004127
Buildings with Slight Damage over 50 years baseline = 285.468515
Buildings with Slight Damage over 50 years retrofit =  256.700495
Probability of Buildings with Slight Damage over 50 years baseline = 1.61836
Probability of Buildings with Slight Damage over 50 years retrofit = 1.31683
Buildings with Moderate Damage over 50 years baseline = 61.33992
Buildings with Moderate Damage over 50 years retrofit = 57.530215
Probability of Buildings with Moderate Damage over 50 years baseline = 0.29881
Probability of Buildings with Moderate Damage over 50 years retrofit = 0.26333
Buildings with Extensive Damage over 50 years baseline = 30.541315
Buildings with Extensive Damage over 50 years retrofit = 29.895915
Probability of Buildings with Extensive Damage over 50 years baseline = 0.143125
Probability of Buildings with Extensive Damage over 50 years retrofit = 0.139465
Buildings with Complete Damage over 50 years baseline = 42.49942
Buildings with Complete Damage over 50 years retrofit = 41.5053
Probability of Buildings with Complete Damage over 50 years baseline = 0.25127
Probability of Buildings with Complete Damage over 50 years retrofit = 0.19617
Collapsed Buildings over 50 years baseline = 3.782255
Collapsed Buildings over 50 years retrofit = 1.740192
Probability of Collapsed Buildings over 50 years baseline = 0.026762
Probability of Collapsed Buildings over 50 years retrofit = 0.01544**

**Comment by phil-evans** [comment]
ready to review

**Comment by drotheram** [comment]
Looks better, waiting on fixed PSRA tiles to before we can close

**Comment by wkhchow** [comment]
New max updates:

**CSD level**
~~Average Annual Fatalities baseline = 0.902588~~
Average Annual Fatalities baseline = 0.9026128279
~~Average Annual Fatalities retrofit = 0.378745~~
Average Annual Fatalities retrofit = 0.3787599068

~~Annual Probability of Fatality baseline = 0.000007~~
Annual Probability of Fatality baseline = 0.0000071514
~~Annual Probability of Fatality retrofit = 0.000005~~
Annual Probability of Fatality retrofit = 0.0000050413

**SAUID level**
~~Average Annual Fatalities baseline = 0.027641~~
Average Annual Fatalities baseline = 0.0276407533
~~Average Annual Fatalities retrofit = 0.007526~~
Average Annual Fatalities retrofit = 0.0110009004

~~Annual Probability of Fatality baseline = 0.00299~~
Annual Probability of Fatality baseline = 0.0000146418
~~Annual Probability of Fatality retrofit = 0.000008~~
Annual Probability of Fatality retrofit = 0.0000075126

**Comment by drotheram** [comment]
@phil-evans There was a mistake with some of these values

**Comment by anthonyfok** [comment]
I am experimenting with changing the "Max legend value" etc. inside WordPress, using only baseline maximum, as follows:

Average Annual Fatalities: /wp-admin/post.php?post=561&action=edit&lang=en
* CSD: Max legend value: 0.99 → 0.9026128279
* SAUID: Max legend value: 0.0032 → 0.0276407533  ← this seems to turn more areas into cream colour?

Annual Probability of Fatality: /wp-admin/post.php?post=562&action=edit&lang=en
* CSD: Custom Scale Values: 1: 0, 2: 0.000001, 3: 0.000002, 4: 0.000003, 5: 0.000004, 6: 0.000005, 7: 0.000006, 8: 0.000007
    → Max legend value: 0.0000071514
* SAUID: Custom Scale Values: 1: 0, 2: 0.0004, 3: 0.0008, 4: 0.0012, 5: 0.0016, 6: 0.002, 7: 0.0024, 8: 0.0028, 9: 0.0032
    → Max legend value: 0.0000146418

The very last change (max value for SAUID for Annual Probability of Fatality does make it look more colourful.  Example for Victoria:

![Screenshot from 2022-10-19 07-01-05](https://user-images.githubusercontent.com/1274764/196700168-40f49f69-9d76-4111-907b-5cc4e40cabce.png)
![Screenshot from 2022-10-19 07-01-10](https://user-images.githubusercontent.com/1274764/196700304-6e702c0a-be64-41fd-a462-fc3ba4018adc.png)

I probably should follow @phil-evans's Custom Scale Values to make the numbers in the bottom scale legend (?) look more even?  What do you think @drotheram and @wkhchow?

**Comment by wkhchow** [comment]
I think the change looks good as you can now see the differences much more clearly. Does the bottom legend scale automatically change once you adjust the max values?

**Comment by anthonyfok** [comment]
Yes, the bottom legend scale changes automatically.  And there are two ways to do it, one with "Max legend value" where the system assign 9 steps linearly; another with "Custom Scale Values" where the number of steps and their values can be customized.  Thanks to @phil-evans for the design!
