### ISSUE TITLE
[ISSUE 8] Links, email addresses and text on website

### ISSUE THREAD

**Issue by anthonyfok** [OpenDRR/riskprofiler#87]
@tieganh wrote on Thu 2022-10-13 evening:

Found some places where the word ‘here’ should be a link, but isn’t. See example, under the data dictionaries. Also for the NHSL the word ‘here’ should be a link, not next to the link. Top of the downloads page also says to refer to training videos ‘here’ that don’t exist yet. Omit this sentence.

![Screen Shot 2022-10-13 at 8 08 25 PM](https://user-images.githubusercontent.com/1274764/196286435-8a8dbb7b-c87d-4b5a-9ca3-f72a3e1ed94e.png)

Related, on the ‘contact us’ page, we need to leave out the seismic risk email address as it doesn’t exist yet. We can use my email if we need to pick one for the meantime. Also the first paragraph is repetitive to the second, and the little subheader blurb about launch on Oct 20, 2022 should be changed to say something about it being a ‘soft’ launch with a full scale launch planned for March.

![Screen Shot 2022-10-13 at 8 10 17 PM](https://user-images.githubusercontent.com/1274764/196287298-8285ceb9-3080-4620-8716-6cd7f3852b1c.png)

**Comment by anthonyfok** [comment]
@JulieVdV replied on Fri 2022-10-14 morning:

@DamonU2 can you confirm the link to download the PSRA data dictionary?

**Comment by anthonyfok** [comment]
@JulieVdV later added:

All changes made except linking the PSRA data dictionary excel file. Julie/@anthonyfok to link when Damon provides.

**Comment by anthonyfok** [comment]
@DamonU2 replied on Fri 2022-10-14 morning:

Actual links: https://github.com/OpenDRR/seismic-risk-model/releases/download/v1.0.0/psra_attributes_en.xlsx
https://github.com/OpenDRR/seismic-risk-model/releases/download/v1.0.0/psra_attributes_fr.xlsx

For code: https://github.com/OpenDRR/seismic-risk-model/releases/latest/download/psra_attributes_en.xlsx
https://github.com/OpenDRR/seismic-risk-model/releases/latest/download/psra_attributes_fr.xlsx

Should probably just use the second set regardless

**Comment by anthonyfok** [comment]
Thank you @DamonU2!  I have just added https://github.com/OpenDRR/seismic-risk-model/releases/latest/download/psra_attributes_en.xlsx to the "here" under Probabilistic Earthquake Risk Assessment Data Dictionary under Other Downloads on the English "Download Data" page.

I took the liberty of making the following changes too:

* Replace the link to Earthquake Scenario Risk Assessment Data Dictionary with https://github.com/OpenDRR/earthquake-scenarios/releases/latest/download/dsra_attributes_en.xlsx (instead of the now outdated v1.1.0)
* Replace "Excel files" with "Excel spreadsheet files"
* Replace "Open DRR" with "OpenDRR", but please correct me if I am wrong.
* Replace instances of double spaces with single space.

The link for the Data Dictionary Excel spreadsheet in French provided by @DamonU2 hasn't been added yet.  Will revisit when French pages are restored after the soft launch.

**Comment by drotheram** [comment]
Closed reviewed and deployed on RiskProfiler.ca
