### ISSUE TITLE
[ISSUE 9] French site lack real translation; need to deactivate temporarily for soft launch?

### ISSUE THREAD

**Issue by anthonyfok** [OpenDRR/riskprofiler#88]
@tieganh wrote on Thu 2022-10-13 evening:

How are we handling the lack of translations so far? Right now we have live buttons to go to the French site, but when I click on them the site looks pretty weird. No header, no way to navigate. Perhaps we should deactivate the French buttons for now?

![Screen Shot 2022-10-13 at 8 12 40 PM](https://user-images.githubusercontent.com/1274764/196293814-8d3e05c6-e303-4a4d-a760-5b104c494106.png)

I think that’s all I notice that needs attention at the moment. Sorry to send such a long list - hopefully they’re all quick fixes!

**Comment by anthonyfok** [comment]
@phil-evans replied on Fri 2022-10-14 morning:

the French side definitely seems to have fallen apart quite a bit due to the scale of the structural & content changes that have happened since it was first created. i’ll do what i can to tidy it up but for the purpose of next week’s launch i’d definitely suggest hiding the language buttons as there’s no time to get the actual translated content in

**Comment by anthonyfok** [comment]
@JulieVdV replied on Fri 2022-10-14 morning:

Agreed. @phil-evans Can you hide the French site?

**Comment by anthonyfok** [comment]
@anthonyfok added on Fri 2022-10-14 morning

Probably just hiding the button (which is the easiest), but if people can still see the French pages if they were to add /fr manually in the path name.

Hope we are the only "people" who would do that :grin:, for developmental purpose of course.

_Update on Mon 2022-10-17 afternoon:_
It looks like @phil-evans has already hidden the "Français" button on the development server!  He must have done it before the end of Friday code push as the change is already in our local test static version.  Thanks @phil-evans!

**Comment by drotheram** [comment]
New issue required for adding French translation to web application
