### ISSUE TITLE
Removed new scenarios not completely removed in WordPress database?

### ISSUE THREAD

**Issue by anthonyfok** [OpenDRR/riskprofiler#89]
While examining wp-app/site/assets/plugins/simply-static/debug.txt from a recent run, I noticed:

* /scenario/duncan/ (and French equivalent) is referred to but gives HTTP 404 error.
* /scenario/burwash-landing/ (and French equivalent) is referred to and actually contains content.

Probably should remove all traces of them.

**Comment by phil-evans** [comment]
@anthonyfok the 'duncan' post still exists but its status is set to draft so it doesn't show on the frontend. burwash is still published and i wasn't aware that it needed to be removed?

**Comment by anthonyfok** [comment]
@phil-evans Thank you for your follow-up and explanation!

There were initially 6 new scenarios, but two have been removed due to errors, one of them being Duncan, and another I thought were Burwash Landing but I could be wrong.  (Good catch!)  Let me double-check and get back to you.  Many thanks!

**Comment by anthonyfok** [comment]
@phil-evans Good catch!  You're right: Burwash Landing is an important scenario that definitely needs to be kept for sure, as fellow teammates reminded me.  The two scenarios that need to be removed were "Masset" and "Duncan".  Since the Duncan scenario may come back in the future, I think it is good that it is kept as Draft.

Thank you so much @phil-evans!  I'm hereby closing this issue as it is not a bug.
